









export const LOCALSTORAGE_HIDE_FIRST_VIEW = '0'
export const LOCALSTORAGE_STAY_CONNECTED = '1'
export const LOCALSTORAGE_THEME = '2'
export const LOCALSTORAGE_LANG = '3'

export const LOCALSTORAGE_WINDOW_HOME = '4'
export const LOCALSTORAGE_WINDOW_SETTINGS = '5'
export const LOCALSTORAGE_WINDOW_CHAT = '6'
export const LOCALSTORAGE_CHAT_RESIZE = '7'
export const LOCALSTORAGE_WINDOW_STORE = '8'
export const LOCALSTORAGE_APPDATA_KEYCODE = '9'
export const LOCALSTORAGE_APPDATA_ENTITY_PLAYER = 'a'
export const LOCALSTORAGE_APPDATA_INVENTORY = 'b'
export const LOCALSTORAGE_APPDATA_WALLET = 'c'
export const LOCALSTORAGE_APPDATA_GAME = 'd'
export const LOCALSTORAGE_WINDOW_UPGRADE = 'e'
export const LOCALSTORAGE_LAST_SERVER_SAVE = 'f'
export const LOCALSTORAGE_WINDOW_INVENTORY = 'g'
export const LOCALSTORAGE_APPDATA_HEROES_USED = 'h'
export const LOCALSTORAGE_WINDOW_QUEST = 'i'
export const LOCALSTORAGE_APPDATA_HEROES = 'j'
export const LOCALSTORAGE_APPDATA_SETTINGS = 'k'
export const LOCALSTORAGE_CAM = 'l'
export const LOCALSTORAGE_EFFECT_PREF = 'm'
export const LOCALSTORAGE_PRETTY_PRINT = 'n'
export const LOCALSTORAGE_APPDATA_QUEST = 'o'
export const LOCALSTORAGE_WINDOW_STATS = 'p'
export const LOCALSTORAGE_WINDOW_MODO = 'q'
export const LOCALSTORAGE_APPDATA_BONUS = 'r'
export const LOCALSTORAGE_APPDATA_STUDENT = 's'

